#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Compiling libraries
wmake -j8 libraries/numericalMethods
wmake -j8 libraries/porousModels
wmake -j8 libraries/reactionModels
wmake -j8 libraries/toolsGIS
wmake -j8 libraries/porousBoundaryConditions

# Compiling solvers 
wmake -j8 solvers/impesFoam
wmake -j8 solvers/anisoImpesFoam
wmake -j8 solvers/groundwaterFoam
wmake -j8 solvers/porousScalarTransportFoam
wmake -j8 solvers/porousScalarTransport2DFoam
wmake -j8 solvers/groundwater2DFoam
wmake -j8 solvers/groundwaterTransport2DFoam
wmake -j8 solvers/groundwaterTransportFoam
wmake -j8 solvers/stationaryGroundwater2DFoam
wmake -j8 solvers/stationaryGroundwaterFoam

# Compiling utilities
wmake -j8 utilities/darcyFoam
wmake -j8 utilities/setBoundaryHeadPressure
wmake -j8 utilities/setFieldsFromXY
wmake -j8 utilities/setFieldsFromMNT
